In [18]:
import numpy as np 
import pandas as pd

In [ ]:
flats=pd.read_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\Flats\flats_cleaned.csv')
houses=pd.read_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\independent_houses\houses_cleaned.csv')

In [20]:
df=pd.concat([flats,houses],ignore_index=True)

In [21]:
df

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,na,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,na,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,na,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3956,4 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,5.50,30556.0,1800.0,Plot area 200(167.23 sq.m.),4,4,3,"pooja room,study room,servant room","Sector 26 Gurgaon, Gurgaon, Haryana",2.0,North-East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, g block, dlf phase-1, gurga...","['10 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'High Ceiling...",NaN
3957,3 Bedroom House for sale in DLF Phase 2,house,dlf city plots phase 2,4.25,31481.0,1350.0,Plot area 150(125.42 sq.m.),3,2,3,study room,"DLF Phase 2, Gurgaon, Haryana",2.0,North,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...","Residential house, k block, dlf phase-2, gurga...",NaN,"['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3958,3 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,4.50,33333.0,1350.0,Plot area 150(125.42 sq.m.),3,3,2,"study room,servant room","Sector 26 Gurgaon, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block 150 sq.Yds , dlf ph...","['6 Fan', '20 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
3959,3 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,3.25,33129.0,981.0,Plot area 109(91.14 sq.m.),3,3,3,study room,"Sector 26 Gurgaon, Gurgaon, Haryana",2.0,West,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block, dlf phase-1, gurga...","['5 Fan', '16 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
3960,3 Bedroom House for sale in Bissar,house,silverglades tarudhan valley golf resort,3.60,14815.0,2430.0,Plot area 270(225.75 sq.m.),3,3,2,"pooja room,study room,servant room,others","Bissar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,This 3 bhk house for sale in bissar is an idea...,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...",NaN

In [22]:
df=df.sample(df.shape[0],ignore_index=True)

In [23]:
df

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 61 Gurgaon,flat,pioneer park,1.60,11594.0,1380.0,Carpet area: 1380 (128.21 sq.m.),2,2,2,servant room,"Sector 61 Gurgaon, Gurgaon, Haryana",21.0,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Hong Kong Bazaar...",Check out this 2 bhk flat for sale in pioneer ...,"['2 Wardrobe', 'No AC', 'No Bed', 'No Chimney'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction3 out of..."
1,2 BHK Flat in Sector-33 Sohna,flat,godrej nature plus,1.15,11558.0,995.0,Carpet area: 92.44,2,2,2,na,"Tower G 15th Floor, Sector-33 Sohna, Gurgaon, ...",15.0,NaN,Dec 2023,"['Signature Global Infinity Mall Sohna', 'Bads...",1.A one-Of-Its-Kind home with three pillars of...,"['3 Fan', '1 Exhaust Fan', '5 Light', 'No AC',...","['Intercom Facility', 'Lift(s)', 'Swimming Poo...",NaN
2,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,NaN,NaN,NaN,Plot area 350(292.64 sq.m.),5,5,3,na,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."
3,4 BHK Flat in Sector 70A Gurgaon,flat,bptp astaire gardens,1.60,8658.0,1848.0,Super Built up area 1848(171.68 sq.m.)Built Up...,4,4,3,"study room,others","H33, Sector 70A Gurgaon, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Airia Mall'...",Bptp astaire gardens is one of gurgaon's most ...,"['1 Fan', '1 Light', '2 Chimney', '4 AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."
4,3 BHK Flat in Sector 104 Gurgaon,flat,ats triumph,1.75,7641.0,2290.0,Super Built up area 2290(212.75 sq.m.)Carpet a...,3,4,3+,"pooja room,study room,servant room,others","Sector 104 Gurgaon, Gurgaon, Haryana",12.0,North-West,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","This 3 bhk flat is located in ats triumph, whi...","['4 Wardrobe', '7 Fan', '19 Light', '1 Chimney...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area4 out of 5', 'Construction5 out of..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3956,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,1.60,8205.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,5,3,servant room,"Sector 70 Gurgaon, Gurgaon, Haryana",6.0,North,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Shree vardhman victoria Located spread over 11...,"['3 Wardrobe', '1 Modular Kitchen', 'No AC', '...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
3957,2 BHK Flat in Sector 65 Gurgaon,flat,m3m heights,1.99,15793.0,1260.0,Super Built up area 1260(117.06 sq.m.),2,2,2,na,"Sector 65 Gurgaon, Gurgaon, Haryana",26.0,NaN,Dec 2023,"['Rapid Metro Sector 56', 'M3m 65th Avenue Mal...",We are the proud owners of this 2 bhk apartmen...,[],NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3958,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.60,13913.0,1150.0,Carpet area: 1150 (106.84 sq.m.),2,2,2,na,"Sector 61 Gurgaon, Gurgaon, Haryana",4.0,NaN,Under Construction,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to golf course extension. Opposite 5 star...,[],"['Lift(s)', 'Swimming Pool', 'Fitness Centre /...",NaN
3959,4 BHK Flat in Sector 92 Gurgaon,flat,sare crescent parc,0.90,4278.0,2104.0,Super Built up area 1870(173.73 sq.m.),4,5,3+,"servant room,others","Sector 92 Gurgaon, Gurgaon, Haryana",14.0,North-East,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Fully furnished. Modular kitchen. Renovated al...,[],"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Management4 out of 5', 'Green Area4 out of 5..."
3960,2 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,0.90,8159.0,1103.0,Super Built up area 1103(102.47 sq.m.),2,2,2,"study room,others","Sector 89 Gurgaon, Gurgaon, Haryana",2.0,East,Within 6 months,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",1 room in basement and open terrace.,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [ ]:
df.to_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\flat_house_data.csv',index=False)