In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [9]:
df=pd.read_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\flat_house_data_missing_value_imputation.csv')

In [10]:
latlong = pd.read_csv(r'D:\vs code projects\rental_analysis\pages\latlong.csv')

In [11]:
latlong['latitude'] = latlong['coordinates'].str.split(',').str.get(0).str.split('°').str.get(0).astype('float')
latlong['longitude'] = latlong['coordinates'].str.split(',').str.get(1).str.split('°').str.get(0).astype('float')

In [12]:
latlong.head()

     sector             coordinates  latitude  longitude
0  sector 1  28.3663° N, 76.9456° E   28.3663    76.9456
1  sector 2  28.5095° N, 77.0320° E   28.5095    77.0320
2  sector 3  28.4909° N, 77.0176° E   28.4909    77.0176
3  sector 4  28.4738° N, 77.0107° E   28.4738    77.0107
4  sector 5  28.4794° N, 77.0176° E   28.4794    77.0176

In [13]:
new_df = df.merge(latlong, on='sector')

In [16]:
new_df.dtypes

property_type          str
society                str
sector                 str
price              float64
price_per_sqft     float64
bedRoom              int64
bathroom             int64
balcony                str
floorNum           float64
agePossession          str
built_up_area      float64
study room           int64
servant room         int64
store room           int64
pooja room           int64
others               int64
furnishing_type      int64
luxury_score         int64
coordinates            str
latitude           float64
longitude          float64
dtype: object

In [17]:
group_df = new_df.groupby('sector')[['price','price_per_sqft','built_up_area','latitude','longitude']].mean()

In [18]:
group_df

                price  price_per_sqft  built_up_area  latitude  longitude
sector
gwal pahari  3.192222     9585.777778    3056.166667   28.4484    77.0210
manesar      0.966562     4656.968750    2019.700000   28.3515    76.9428
sector 1     1.860000     8249.833333    2327.833333   28.3663    76.9456
sector 102   1.681327    10641.053097    1545.486726   28.4750    76.9715
sector 103   1.441556     7424.555556    1804.533333   28.4949    76.9845
...               ...             ...            ...       ...        ...
sector 92    0.931346     5906.298077    1574.492115   28.4079    76.9153
sector 93    0.808182     8516.363636     941.272727   28.4153    76.9326
sector 95    0.486610     5595.305085    1011.694915   28.4172    76.9081
sector 99    1.695625     7163.500000    1998.000000   28.4640    76.9614
sector 99a   0.816562     6270.750000    1195.875000   28.4561    76.9542

[104 rows x 5 columns]

In [22]:
fig = px.scatter_mapbox(group_df, lat="latitude", lon="longitude", color="price_per_sqft", size='built_up_area',
                  color_continuous_scale=px.colors.cyclical.IceFire, zoom=10,
                  mapbox_style="open-street-map",text=group_df.index)
fig.show()

C:\Users\msi 1\AppData\Local\Temp\ipykernel_17800\860414701.py:1: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.scatter_mapbox(group_df, lat="latitude", lon="longitude", color="price_per_sqft", size='built_up_area',

In [ ]:
new_df.to_csv('data_viz1.csv',index=False)